name: Build SunamoCssGenerator

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoCssGenerator
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoCssGenerator/SunamoCssGenerator.csproj

    - name: Build
      run: dotnet build SunamoCssGenerator/SunamoCssGenerator.csproj --configuration Release --no-restore

  test:
    name: Test SunamoCssGenerator.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoCssGenerator.Tests/SunamoCssGenerator.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoCssGenerator.Tests/SunamoCssGenerator.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoCssGenerator.Tests/SunamoCssGenerator.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
